all: tc1 tc2 tc3 tc4;

tc1: test_case1.cpp myfs.h;
	g++ test_case1.cpp -lrt -lpthread -o tc1

tc2: test_case2.cpp myfs.h;
	g++ test_case2.cpp -lrt -lpthread -o tc2

tc3: test_case3.cpp myfs.h;
	g++ test_case3.cpp -lrt -lpthread -o tc3

tc4: test_case4.cpp myfs.h;
	g++ test_case4.cpp -lrt -lpthread -o tc4
